template: |
    # What’s New in Sunburst.UpdatedWPF $RESOLVED_VERSION

    $CHANGES

    -----

    Sunburst.WPF follows semantic versioning.

categories:
    - title: '🚀 Features'
      labels: ['feature']
    - title: '🐛 Bug Fixes'
      labels: ['bugfix']
    - title: '📘 Documentation'
      labels: ['documentation']
    - title: '🧰 Maintenance & Dependencies'
      labels: ['maintenance', 'dependencies']

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

version-resolver:
    major:
        labels: ['bump-major-version']
    minor:
        labels: ['bump-minor-version']
    patch:
        labels: ['bump-patch-version']
    default: patch
